### ISSUE TITLE
Vary: Origin header should always be present

### ISSUE THREAD

**Issue by xealot** [rs/cors#10]
Right now the `Vary: Origin` response header is only applied when there is an `Origin` header in the request. I believe this should be considered a bug because conditionally returning the header based on the presence of an `Origin` will poison intermediate caches (Varnish, Akamai, any CDN, etc).

Since you can issue a request without an Origin an intermediate cache will hang on to the return value. Next time when a cross domain request comes in with an `Origin` the intermediate cache won't know to `Vary` by `Origin` and will return the non-CORS response.

**Comment by rs** [comment]
Nice catch, thx.
