### ISSUE TITLE
Implement the Strict-Transport-Security header with its rules.

### ISSUE THREAD

**Issue by gonzalezlrjesus** [rs/cors#105]
Hi everyone, I am building a Rest API, I just want to allow HTTPS connection with Header: [**Strict-Transport-Security**](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security).

But CORS only has the option to register it as a permitted header. 

	c := cors.New(cors.Options{
		AllowedOrigins:   []string{"*"},
		AllowCredentials: true,
		AllowedMethods:   []string{"POST", "GET", "OPTIONS", "PUT", "DELETE", "PATCH"},
		AllowedHeaders:   []string{"Accept", "Content-Type", "Strict-Transport-Security", "Origin", "X-Requested-With", "Content-Length", "Accept-Encoding", "Cache-Control", "Authorization"},
		// Enable Debugging for testing, consider disabling in production
		Debug: false,
	})

I would like if it is possible to implement  the header with its rules. it should be like this:

**Strict-Transport-Security: max-age = 31536000; includeSubDomains.**

**Comment by rs** [comment]
This is not part of the CORS spec.

**Comment by jub0bs** [comment]
Besides, [`Strict-Transport-Security`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) is a _response_ header, not a _request_ header; listing it as an allowed request header name in one's CORS configuration makes no sense.
