### ISSUE TITLE
public isOriginAllowed ?

### ISSUE THREAD

**Issue by alicebob** [rs/cors#114]
Hi,

thanks for the library!

We're using this, and now we want to add some websockets with https://pkg.go.dev/github.com/gorilla/websocket .
To deal with Origin stuff gorilla/websocket needs a callback which returns true:
https://pkg.go.dev/github.com/gorilla/websocket?utm_source=godoc#Upgrader -> CheckOrigin() .

The existing `isOriginAllowed()` does this check already, and would be perfect. We then have a single place where our CORS list of domains is set. But the function is not exported. Would it be possible to export it? I'm happy to make a PR if that helps.

**Comment by alicebob** [comment]
I added what I'm looking for in a fork: https://github.com/engagespark/cors (boldly in the master branch).

**Comment by rs** [comment]
Please send a PR
