### ISSUE TITLE
publish latest code

### ISSUE THREAD

**Issue by missinglink** [rs/cors#116]
Heya,

I installed version `github.com/rs/cors v1.7.0` (latest) and noticed that the `OPTIONS` preflight request returns `200 OK` instead of `204 No Content` ([as shown in `master`](https://github.com/rs/cors/blob/master/cors.go#L214)).

```bash
go get -u github.com/rs/cors

grep -C1 WriteHeader $GOPATH/src/github.com/rs/cors/cors.go

			} else {
				w.WriteHeader(http.StatusOK)
			}
```

After a bit of digging it seems that https://github.com/rs/cors/commit/be1c7e127af9fce006600894df5c5731d99cdc82 hasn't been published as a module release yet.

Would it be possible to publish a new release which includes that commit?

**Comment by rs** [comment]
done
