### ISSUE TITLE
Problem with .local url

### ISSUE THREAD

**Issue by spartakos87** [rs/cors#122]
Hello, I have a problem with CORS when I am trying to call my api from <name>.local address
![Screenshot 2021-11-26 185850 (2)](https://user-images.githubusercontent.com/5782594/143624251-e376bccf-c2d1-4450-9459-f17bbad2abf4.png)

I use mux and my setup for CORS is,
`c := cors.New(cors.Options{
		AllowedOrigins:   []string{"*"},
		AllowCredentials: true,
		AllowedMethods:   []string{"GET", "POST", "DELETE"},

		// Enable Debugging for testing, consider disabling in production
		Debug: true,
	})
`
Do I need any special set up for this?
I find out that I need to set up the header  'Access-Control-Allow-Private-Network' as true, how can I set up this one?
Thanks

**Comment by cvermilion** [comment]
Hi @spartakos87, `Options.AllowPrivateNetwork` was added in https://github.com/rs/cors/pull/127, which may be what you need.

**Comment by JohnMaguire** [comment]
Ran into this as well. @rs Any idea when the next release might get tagged?

**Comment by rs** [comment]
Tagged

**Comment by jub0bs** [comment]
@rs You could close this issue, at this stage.
