### ISSUE TITLE
Should OPTIONS response include Access-Control-Allow-Origin?

### ISSUE THREAD

**Issue by mb-dev** [rs/cors#13]
I've setup cors with default server. When running:

curl -D - -X OPTIONS -H 'Origin: http://www.plot-my-trip.local.com:8080' http://www.plot-my-trip.local.com:4000/api/auth/get-user

    Vary: Origin
    Vary: Access-Control-Request-Method
    Vary: Access-Control-Request-Headers
    Date: Thu, 20 Aug 2015 00:05:01 GMT
    Content-Length: 0
    Content-Type: text/plain; charset=utf-8

Notice there's no Access-Control-Allow-Origin header. 

When trying to access the above API using Javascript in Chrome, I see the error in the console:

    http://www.plot-my-trip.local.com:4000/api/auth/get-user. No 'Access-Control-Allow-Origin' header 
    is present on the requested resource. Origin 'http://www.plot-my-trip.local.com:8080' is 
    therefore not allowed access.

**Comment by rs** [comment]
Can you activate the logs because this header is set unconditionally on preflight requests (see https://github.com/rs/cors/blob/master/cors.go#L255).

**Comment by mb-dev** [comment]
Scratch that. Turns out I did not add Authorization to AllowedHeaders so it did not return the Access-Control-Allow-Origin.

**Comment by rs** [comment]
ok np :)

**Comment by mb-dev** [comment]
It would be more clear if these lines from https://github.com/rs/cors/blob/master/cors.go#L232

    headers.Add("Vary", "Origin")
    headers.Add("Vary", "Access-Control-Request-Method")
    headers.Add("Vary", "Access-Control-Request-Headers")

Would be sent later after all checks are passed.

**Comment by rs** [comment]
True but it would defeat the goal of those headers. A request rejected by one of the checks could then be cached and served to requests with different set of headers (i.e: valid ones).

**Comment by arekkas** [comment]
Thanks, this saved my life.
