### ISSUE TITLE
gin wrapper default status

### ISSUE THREAD

**Issue by Limm-jk** [rs/cors#145]
I feel strange that the response status code for the preflight request in the gin wrapper is fixed at 200.

I wonder if we can solve it as follows, but I'm curious about your opinion.
1. Fix it to 204 because the internal default value is 204
2. Save to corsWrapper like OptionPasstrough
3. Create a getter in the Cors structure

If you let me know your opinion, I would like to revise it and make a PR. I'm using it so well! Thank you always.

**Comment by jub0bs** [comment]
@Limm-jk I'm not the maintainer of this library, but I'd be in favour of 1 and 2, but not 3 (because it's unnecessary).
