### ISSUE TITLE
Access-Control-Expose-Headers should be sent in preflight response

### ISSUE THREAD

**Issue by damien-talos** [rs/cors#153]
Currently, the `Access-Control-Expose-Headers` header is only sent in the real response, not the preflight response.
This means that it has no effect, since the browser only uses the headers sent on the preflight response.

Is there any reason why the writing of the headers, is not shared between preflight and actual handlers?

**Comment by jub0bs** [comment]
@damien-talos You're mistaken: the `Access-Control-Expose-Headers` belong in the actual response, not in the preflight response. See [the relevant section of the Fetch standard](https://fetch.spec.whatwg.org/#http-access-control-expose-headers):

> An HTTP response to **a CORS request that is not a CORS-preflight request** can also include the following header:
>
> `Access-Control-Expose-Headers`
> * Indicates which headers can be exposed as part of the response by listing their names.

(my emphasis)

**Comment by jub0bs** [comment]
@rs I think you can close this issue now. 😇
