### ISSUE TITLE
Allowing methods that are not uppercase should be possible but isn't

### ISSUE THREAD

**Issue by jub0bs** [rs/cors#158]
Although method names are case-sensitive, rs/cors takes the unusual approach of [normalising method names by uppercasing them](https://github.com/rs/cors/blob/fcebdb403f4d4585c705318c0e4d6d05a761a4ab/cors.go#L320):

> ```go
> // Normalize options
> // Note: for origins and methods matching, the spec requires a case-sensitive matching.
> // As it may error prone, we chose to ignore the spec here.
> ```

Such unwarranted case normalisation causes problems for clients that send requests whose method is not uppercase—and not some case-insensitive match for one of `DELETE`, `GET`, `HEAD`, `OPTIONS`, `POST`, or `PUT`, [names for which the Fetch standard carves out an exception](https://fetch.spec.whatwg.org/#concept-method-normalize). Here is an example:

```go
c := cors.New(cors.Options{
  AllowedOrigins: []string{"https://example.com"},
  AllowedMethods: []string{"patch"},
})
```

Assume then that a client running in the context of Web origin `https://example.com` in a Fetch-compliant browser sends a patch request (note the lower case) to the server. As rs/cors internally normalises method names to uppercase, the preflight response would contain

```http
Access-Control-Allow-Methods: PATCH
```

as opposed to

```http
Access-Control-Allow-Methods: patch
```

Browsers rule this as a mismatch and fail CORS preflight with an error message of this kind:

> Access to fetch at [REDACTED] from origin ‘https://example.com/’ has been blocked by CORS policy: Method patch is not allowed by Access-Control-Allow-Methods in preflight response.

For this reason, rs/cors should not normalise method names. More about this in [one of my recent blog posts](https://jub0bs.com/posts/2023-02-08-fearless-cors/#violation-of-the-case-sensitivity-of-method-names).

**Comment by rs** [comment]
Please submit a PR

**Comment by jub0bs** [comment]
@rs I would if I didn't have [my own CORS middleware library](https://pkg.go.dev/github.com/jub0bs/fcors) for Go.

**Comment by rs** [comment]
Great mindset

**Comment by jub0bs** [comment]
@rs No need to take it personally. I've already produced _one_ CORS middleware library, and my time is limited. Besides, making issues in existing libraries more visible doesn't imply that I'm going to fix them.

**Comment by jub0bs** [comment]
@rs I'm not sure how big of a deal this is, but [directly assigning the `Options.AllowedMethods` slice directly to the `cors.Methods` field](https://github.com/rs/cors/commit/41a5eefa98d3b90b0720c1d4508abefd219d5370#diff-bf80d8fbedf172fab9ba2604da7f7be972e48b2f78a8d0cd21619d5f93665895R184) may be problematic. For example, through a reference to the `cors.Options` value passed to `cors.New`, users can now change elements of the `cors.Methods` slice _after_ middleware instantiation:

```go

opts := cors.Options{
    AllowedOrigins: []string{"http://example.com"},
    AllowedMethods: []string{"GET"},
}

c := cors.New(opts)

opts.AllowedMethods[0] = "PUT" // middleware c now allows method PUT instead of GET
```

Such mutability stands in the way of concurrency safety, and middleware are typically invoked in a concurrent setting. You may want to err on the side of caution and opt for some defensive copying:

```go
c.allowedMethods = slices.Clone(options.AllowedMethods)
```

Just a thought.
