### ISSUE TITLE
AllowedOrigins doesn't block unlisted origins

### ISSUE THREAD

**Issue by Nightsee** [rs/cors#167]
I am trying to block all requests comming from other than the specified origin, but the requests still pass.
my code looks like this: 

`router := httprouter.New()
 ...
c := cors.New(cors.Options{
      AllowedOrigins: []string{"http://localhost:3020"},
})
handler := c.Handler(router)`

i tried to use AllowOriginFunc and print the origin i get nothing.
i am testing the api from localhost:3030 and it's working. why is that and how can i implement what i want ? thanks

**Comment by jub0bs** [comment]
@Nightsee I think your issue stems from a misunderstanding of CORS's purpose. CORS (Cross-Origin Resource Sharing) is for _relaxing_ some of the Same-Origin Policy's restrictions on cross-origin network access for browser-based clients. Contrary to popular belief, CORS is _not_ for blocking requests. See also https://github.com/rs/cors/issues/129

**Comment by jub0bs** [comment]
@Nightsee If you're happy, don't hesitate to close the issue yourself.
