### ISSUE TITLE
cors not adding multiple Access-Control-Allow-Origin entries

### ISSUE THREAD

**Issue by udf2457** [rs/cors#172]
I am loading cors with the following:

```go
corsAllowedHeaders := "Hx-Current-Url,Hx-Request"
corsAllowedOrgins := "https://one.example.com,https://two.example.com"
cors.New(cors.Options{
		AllowedHeaders: strings.Split(corsAllowedHeaders, ","),
		AllowedOrigins: strings.Split(corsAllowedOrgins, ","),
		AllowedMethods: []string{"GET", "POST", "HEAD", "OPTIONS"},
		Debug:          true,
	})
```

But the debug output only shows the first URL being added:
```
Actual response added headers: map[Access-Control-Allow-Origin:[https://one.example.com] Vary:[Origin]]
```

Am I doing something wrong, or is this a bug ?

**Comment by jub0bs** [comment]
The middleware is working as expected in that respect: [according to the Fetch standard](https://fetch.spec.whatwg.org/#cors-check), a response to a CORS request should indeed contain at most one `Access-Control-Allow-Origin` header. If more than one such header is present in a response, [browsers joins their values with the character sequence `, `](https://fetch.spec.whatwg.org/#concept-header-list-get), which makes the CORS check fail ([here](https://stackoverflow.com/questions/72200848/cors-header-access-control-allow-origin-does-not-match/72202727#72202727) is just one example).

**Comment by jub0bs** [comment]
@udf2457 Has my last comment answer your question? Can we close this issue?
