### ISSUE TITLE
Case-sensitive look up on allowed headers map

### ISSUE THREAD

**Issue by EmmEff** [rs/cors#176]
Allowed headers are ingested correctly in initialization and in the call `cors.handlePreflght()`:

https://github.com/rs/cors/blob/3d336ea9b505046d343dfb14f09f19fad17673b4/cors.go#L368

The headers in the request are handled AS IS.

Allowed headers are normalized during initialization: 

https://github.com/rs/cors/blob/3d336ea9b505046d343dfb14f09f19fad17673b4/cors.go#L199

In the function `SortedSet.Subsumes()`, a case-sensitive lookup is done on the map:

https://github.com/rs/cors/blob/3d336ea9b505046d343dfb14f09f19fad17673b4/internal/sortedset.go#L76

This issue surfaced in the v1.11.0 release.

**Comment by rs** [comment]
The spec says headers are sent as a ordered lowercase list. Is there a specific case where this change break something?

**Comment by EmmEff** [comment]
Well it broke my code :)

In my investigation, I was following the docs @ https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS which uses mixed case values in the CSV argument to `Access-Control-Request-Headers` in their examples.

I see the spec is conflicts with that (as you mention)

**Comment by jub0bs** [comment]
@EmmEff The middleware is working as expected. That v1.11.0 broke your code/tests is unfortunate but your tests arguably shouldn't depend on the intricacies of rs/cors so strongly.

>  I was following the docs @ https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS which uses mixed case values in the CSV argument to Access-Control-Request-Headers in their examples.

Indeed:

> ```http
> Access-Control-Request-Headers: X-PINGOTHER, Content-Type
> ```

Nice catch; I understand how that can trip people up. In that case, the right thing to do is open an issue on https://github.com/mdn/content. I'll do so if you don't want to.

**Comment by jub0bs** [comment]
@EmmEff Are you still experiencing problems or can this issue be closed now?
