### ISSUE TITLE
Arbitrary origin allowed in CORS header

### ISSUE THREAD

**Issue by Ashish-walkingn8mare** [rs/cors#177]
using these cors options with go-chi router
`Cors := cors.New(cors.Options{
			AllowedOrigins:   []string{"https://abcd.example.com", "http://localhost:8080"},
			AllowedMethods:   []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
			AllowedHeaders:   []string{"*"},
			ExposedHeaders:   []string{config.GetString(ctx, "csrf.token_header")},
			AllowCredentials: true,
			MaxAge:           300, // Maximum value not ignored by any of major browsers
		})
		r.Use(Cors.Handler)`
		
but requests made from https://abcd.example12345.com are also being allowed
 version github.com/rs/cors v1.8.2

**Comment by rs** [comment]
Can you please show the request/response details?
