### ISSUE TITLE
Wildcard support for AllowedHeaders or add AllowedHeadersFunc

### ISSUE THREAD

**Issue by kilgaloon** [rs/cors#179]
I don't see a support that we can specify something like `X-Header-*`. I think this can be useful for some use cases. Maybe it would be good to add support for the wildcard or provide the func similar to the `AllowOriginFunc`.

**Comment by jub0bs** [comment]
This seems like an odd use case to me... How many such request-header names do you typically need to allow in your CORS configuration?

**Comment by jub0bs** [comment]
This seems like an odd use case to me... How many such request-header names do you typically need to allow in your CORS configuration?

**Comment by jub0bs** [comment]
@kilgaloon Any further comment? Can we close this issue?

**Comment by jub0bs** [comment]
@rs Without feedback from the OP, and in light of a [recent comment of yours](https://github.com/rs/cors/issues/184#issuecomment-2307247534), I'm inclined to reject this suggestion.
