### ISSUE TITLE
Append Accept and Content-Type always

### ISSUE THREAD

**Issue by lancecarlson** [rs/cors#18]
According to this:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Simple_requests

A simple request should at the very least allow these two headers. Do you think it makes sense to whitelist those by default here?

https://github.com/rs/cors/blob/master/cors.go#L144

**Comment by rs** [comment]
From my understanding, that's a spec for the user-agent. Basically the user-agent should consider simple, a request which doesn't customize headers / method outside of this list. A simple request won't generate a pre-flight request nor ask for permission about those headers / methods specifically.
