### ISSUE TITLE
AllowOriginVaryRequestFunc support for adding values to request context

### ISSUE THREAD

**Issue by mackinleysmith** [rs/cors#182]
Hey there! I am working on an API that is used directly from our customer's frontends -- a great analogue would be the way that Google Maps API works; the customer can specify their own domain values that an API key can be used on. When a request is made to my API, I look up the API key in my database from within `AllowOriginVaryRequestFunc`, which hands me the values to be used as `AllowedOrigins`.

Unfortunately, information about that API key and user session are still needed from outside the CORS middleware -- I want my application to have access to them without looking them up in the database a second time. This is where I would normally seek to write to the request context, but unfortunately the interface of `AllowOriginVaryRequestFunc` does not really allow this in any way that I can currently think of.

I think it would be awesome if this function could return the request object, so that I might do something like:
```go
r = r.WithContext(context.WithValue(r.Context(), "some", "data"))
```

I would be happy to submit a PR for this, but first wanted to consult with you on preferences and viability.

Thanks for your time!

**Comment by mackinleysmith** [comment]
Actually, something I thought of to hold me over in the meantime is just to add a second middleware to wrap my usage of this package, and set my values from within it. Then, the cors middleware can just pull the session/api key information off the request context.

Still, I think it would be nice if the context could be altered directly by this package during validation.

**Comment by mackinleysmith** [comment]
Another reason that this would be great is that my needs are not exactly satisfied by https://github.com/rs/cors/issues/167 and https://github.com/rs/cors/issues/129 -- I understand that CORS itself is not intended as a protection mechanism, but I would really like to know whether the origin I received actually passed the validation check, because I really do not want requests to be processed if the API key wasn't configured to allow a particular domain.

Being able to write the result of that check into the request context would help me to handle this in my own application code.

**Comment by jub0bs** [comment]
`AllowOriginVaryRequestFunc` is [partly responsible for handling CORS-preflight requests](https://github.com/rs/cors/blob/1562b1715b353146f279ff7d445b7412e0f1a842/cors.go#L345), not just _actual_ (i.e. non-preflight) CORS requests. Be aware that [CORS-preflight requests never carry any credentials](https://fetch.spec.whatwg.org/#cors-protocol-and-credentials) (whether those managed by the client or by the browser). Therefore, I don't think what you're suggesting could be implemented in `AllowOriginVaryRequestFunc` or any of its friends.

**Comment by mackinleysmith** [comment]
Thanks for the response. After further investigation on my part I completely agree, thank you for helping me through my misunderstandings here. Cheers!
