### ISSUE TITLE
Can't seem to get working with Socket.io

### ISSUE THREAD

**Issue by acoyfellow** [rs/cors#2]
Hi there, thanks for the hard work on cors. Just trying to get it set up Socket.io:
http://stackoverflow.com/questions/27828052/go-socket-io-http-wss-on-one-port-with-cors

Any pointers on where I'm going wrong or how to fix? I'm seeing: 

WebSocket connection to 'wss://api.domain.com/socket.io/?EIO=3&transport=websocket&sid=bWok_LmVKvvS-MxihuxE' failed: WebSocket is closed before the connection is established.
(index):1 XMLHttpRequest cannot load https://api.domain.com/socket.io/?EIO=3&transport=polling&t=1420671018767-829&sid=bWok_LmVKvvS-MxihuxE. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://fiddle.jshell.net' is therefore not allowed access.

**Comment by rs** [comment]
Sorry for my late answer. It looks like you found the solution on stackoverlow. Can we close this issue or do you have something to add?
