### ISSUE TITLE
support for echo v2 engine fasthttp

### ISSUE THREAD

**Issue by hexadecy** [rs/cors#25]
There is an easy way to use echo v2 standard engine with cors.
But with the fasthttp engine, I had to create a fork and rewrite handlePreflight and handleActualRequest. It also add a dep to echo.

Do you want a PR or do I fork it?

**Comment by rs** [comment]
Would the result be free of new dep and still compat with net/http?

**Comment by hexadecy** [comment]
Still compat only but with a complete duplicate of the 2 functions, like handlePreflightEcho(). 
I just learned that echo will soon have a cors middleware built-in.
So I will complete it to have an alternative in case.

**Comment by jadbox** [comment]
It would be great to support Cors with plain fasthttp (without Echo).

**Comment by gaby** [comment]
@hexadecy You closed this but didn't share how it was completed?

@rs Can this be re-open? It would be awesome to have native fasthttp support

**Comment by gaby** [comment]
No worries, adding fasthttp will require adding a dependency in `go.mod`

**Comment by hexadecy** [comment]
@gaby sorry I didn't keep the code.
fasthttp didn't support http2, and the fork https://github.com/fasthttp/http2/issues/3 doesn'thave a lot of support.
