### ISSUE TITLE
Access-Control-Allow-Origin should return * when allowedOriginsAll is true

### ISSUE THREAD

**Issue by hareesh-blippar** [rs/cors#30]
Currently, there is no way to return `"Access-Control-Allow-Origin": "*"` using this library due to https://github.com/rs/cors/blob/master/cors.go#L333

When `allowedOriginsAll = true`,  it is perhaps better to do
```
headers.Set("Access-Control-Allow-Origin", "*")
```
instead of
```
origin := r.Header.Get("Origin")
headers.Set("Access-Control-Allow-Origin", origin)
```

In my case for example, I'm caching responses from multiple origins behind a CDN, and require `"Access-Control-Allow-Origin": "*"` so that the cached response for origin A can be reused for origin B, which is not possible with this library.

**Comment by rs** [comment]
Most of the time, a CDN will keep a separate cache for each domain. Keep in mind that with `Access-Control-Allow-Origin: *` you can't use `withCredentials`. If your goal is just to send a static `Access-Control-Allow-Origin: *`, you don't need this library.
