### ISSUE TITLE
github.com/rs/cors/cors.go:215: cannot convert func literal

### ISSUE THREAD

**Issue by penhauer-xiao** [rs/cors#36]
github.com/rs/cors/vendor/github.com/rs/cors/cors.go:215: cannot convert func literal (type func("golang.org/x/net/context".Context, http.ResponseWriter, *http.Request)) to type xhandler.HandlerFunc

**Comment by mikegleasonjr** [comment]
"Context Handlers" has been removed since `Context` is not part of a `http.Request`.

If you need a context, just use the one in http.Request and use a regular handler.

See #33

**Comment by mvdan** [comment]
@mikegleasonjr you can close this, there is no issue here. It appears OP was not using our vendored dependencies, which includes this package.

**Comment by mikegleasonjr** [comment]
@mvdan I am merely a contributor, I don't have the rights to close it :)

**Comment by penhauer-xiao** [comment]
:)
