### ISSUE TITLE
Pass `r *http.Request` to AllowOriginFunc

### ISSUE THREAD

**Issue by aeneasr** [rs/cors#59]
It's currently not possible to set CORS based on e.g. HTTP Authorization. This is because signature `AllowOriginFunc func(origin string) bool` does no have `r *http.Request`. This makes advanced use cases impossible and the function for anything else than maybe wildcard-based subdomain matching. There's actually a fork that does that (https://github.com/go-chi/cors) but this should really be added here.

**Comment by jub0bs** [comment]
Note to readers of this issue: because `AllowOriginRequestFunc` is [fundamentally flawed](https://github.com/rs/cors/issues/157), it was deprecated in v1.11.0.
