### ISSUE TITLE
go test fails with go 1.11

### ISSUE THREAD

**Issue by rayjohnson** [rs/cors#64]
go test
# github.com/rs/cors
./cors_test.go:402: comparison of function logf == nil is always false
FAIL	github.com/rs/cors [build failed]

**Comment by rs** [comment]
I can't reproduce. What version of go do you have?

**Comment by komuw** [comment]
I'm also **unable** to reproduce this. 
```
go version      
go version go1.11.1 linux/amd64
```

**Comment by rayjohnson** [comment]
$ go version

go version go1.11 darwin/amd64

$ go test

# _/Users/rayj/dev/go/src/github.com/rs/cors

./cors_test.go:402: comparison of function logf == nil is always false

FAIL _/Users/rayj/dev/go/src/github.com/rs/cors [build failed]

**Comment by rs** [comment]
Are you on current master?

**Comment by rs** [comment]
Please reopen if you still experience the issue.
