### ISSUE TITLE
Excuse me, I can't use it in gin router group

### ISSUE THREAD

**Issue by aurora-x1994** [rs/cors#72]
![image](https://user-images.githubusercontent.com/39690273/50043169-6a566d00-00aa-11e9-9697-5e349549b544.png)

I first used the comment code and then used the default, but it doesn't work

It doesn't work, but if you use USE directly on R, it's successful.
![image](https://user-images.githubusercontent.com/39690273/50043191-d76a0280-00aa-11e9-8f70-ccdc9878c81a.png)
Am I missing something? How can I do this?

**Comment by aurora-x1994** [comment]
Solved by opening the debug issue!

**Comment by sno6** [comment]
How did you solve this? @Limerence-1994

**Comment by Limerence-1994** [comment]
> How did you solve this? @Limerence-1994

Not used in group   :）
