### ISSUE TITLE
Understanding benchmarks...

### ISSUE THREAD

**Issue by frederikhors** [rs/cors#74]
I'm new to Go and CORS.

Reading `Readme.md` I was impressed by the "Benchmarks" section.

I do not know if I understood correctly:

- `BenchmarkWithout` means without using CORS?
- `BenchmarkDefault` means using CORS?

**Comment by rs** [comment]
Yes, default is using cors with default settings. You will find all the details in https://github.com/rs/cors/blob/master/bench_test.go.

**Comment by frederikhors** [comment]
@rs, please, can I ask you what it means:

- `BenchmarkPreflight` in "Benchmarks" section?

**Comment by rs** [comment]
It benchmark the handling of CORS preflight requests (aka OPTIONS requests).
