### ISSUE TITLE
Access-Control-Allow-Credentials header duplicated

### ISSUE THREAD

**Issue by sejoDjoseon** [rs/cors#77]
Using angular 7, trying to authenticate with cookies, I use withCredentials: true (httpClient) and the response triggers an error in the browser.
![credentials-headers](https://user-images.githubusercontent.com/19385762/57097741-ce579600-6d18-11e9-903d-cf0e86195d20.png)
![corsOptions](https://user-images.githubusercontent.com/19385762/57097752-d3b4e080-6d18-11e9-8640-7c497c5ecf0d.png)

**Comment by rs** [comment]
You might have another handler adding this header. CORS sets the header (as opposed to adding), so even if already there, the output would always be a unique header.
