### ISSUE TITLE
AllowAll and Access-Control-Expose-Headers.

### ISSUE THREAD

**Issue by yonderblue** [rs/cors#79]
Just a suggestion, since wildcard for Access-Control-Expose-Headers isn't widely supported yet, I would recommend filling Access-Control-Expose-Headers in the AllowAll configuration with the result of whatever is set in the wrapped handler minus any of the 6 default values and other Access-Control-* headers.

**Comment by rs** [comment]
Would you be willing to submit a PR?

**Comment by gaillard** [comment]
Sure thing, PR up.

**Comment by bweston92** [comment]
Any update on this? I think this is causing me some issues.

**Comment by jub0bs** [comment]
> filling `Access-Control-Expose-Headers` [...] with the result of whatever is set in the wrapped handler

I thought about this, and I don't think it can be done. The wrapped handler may write to the response body; in that case, it would be too late for the middleware to include another response header after that.

**Comment by jub0bs** [comment]
@rs Since `Access-Control-Expose-Headers: *` is now supported by all modern browsers, I think you could likely close this issue.
