### ISSUE TITLE
Are all these dependencies actually required in the root package?

### ISSUE THREAD

**Issue by h2non** [rs/cors#92]
I found in `go.mod` a bunch of dependencies that are declared for the root package, but these dependencies are only indeed used in the `examples` folder packages:

https://github.com/rs/cors/blob/master/go.mod#L6-L17

Is there a reason why these non-production dependencies are declared in the root package `go.mod`?

**Comment by rs** [comment]
go mod added them automatically, but they are mot necessary.

**Comment by h2non** [comment]
Ok, cool. Can we get rid of them? It's counterproductive pulling a small dependency like `rs/cors` that downloads a bunch of other large non-related web lib packages.

**Comment by rs** [comment]
Sure, can you please make a PR?

**Comment by h2non** [comment]
There you go: https://github.com/rs/cors/pull/94
