### ISSUE TITLE
The dot character as part of header keys is broking the preflighted requests

### ISSUE THREAD

**Issue by Ariel-dono** [rs/cors#99]
If you run a preflighted request containing the character "." as part of a header key, it is not working.
I made a quick fix, it was just replacing:
`reqHeaders := parseHeaderList(r.Header.Get("Access-Control-Request-Headers"))`
by
`reqHeaders := strings.Split(r.Header.Get("Access-Control-Request-Headers"), ",")`
in "cors.go" file: https://github.com/rs/cors/blob/d4dacab0671f9aedbf3924d3df2a4a95c8c11a87/cors.go#L286.

Then all works as usual, maybe it would be needed a header processing for special characters of naming conventions.

**Comment by Ariel-dono** [comment]
https://httpwg.org/specs/rfc7230.html#rule.token.separators

**Comment by Ariel-dono** [comment]
You even could replace 
https://github.com/rs/cors/blob/d4dacab0671f9aedbf3924d3df2a4a95c8c11a87/utils.go#L28
by 
`// parseHeaderList tokenize + normalize a string containing a list of headers
func parseHeaderList(headerList string) []string {
	regex := regexp.MustCompile(`[()\[\]/:;<=>?@\\{}]+`)
	headerList = regex.ReplaceAllString(headerList, "")
	return strings.Split(headerList, ",")
}`

**Comment by alebeta90** [comment]
Hi @Ariel-dono 

thanks for pointing it out. I just have this issue too.

When is this solution being merge in the code?

thanks

**Comment by rs** [comment]
I need a PR first

**Comment by Ariel-dono** [comment]
I haven't granted the permissions... in order to make the PR... :persevere:

**Comment by Ariel-dono** [comment]
I tried but it was refused on the access to the repository...

**Comment by rs** [comment]
You need to fork the repo first.

**Comment by alebeta90** [comment]
if you need help to work it just let me know :) i could do it too

**Comment by Ariel-dono** [comment]
https://github.com/rs/cors/pull/103
